before_install:
  - "curl -sL https://s3.bixby.io/wad > ~/wad"
  - "chmod +x ~/wad"
install:
  - "travis_retry ~/wad"
script: "bundle exec micron --fork $(find * -maxdepth 0 -type d | grep -v vendor)"
after_script:
  - "rake coverage"
  - "rake coveralls"

language: ruby
rvm:
  - 2.1.1
  - 1.9.3

branches:
  only:
    - master
    - develop

env:
  global:
    - S3_REGION="us-east-1"
    - S3_BUCKET_NAME="io.bixby.gemcache.wad.repo"
    - secure: gxQHylKi0oXowGiNO6jyrXKngte8gp7BohlKTH22MAV+B9q2rZU+8wFpgUHiIvYa9W1E7HxkkvZwwNEeUiRNDTodHGM72cLrUEmrriLWCMT8KSCxFCCCHa3BmnXf9/gVNQ/aEwYwUHpEIWBfIsjpDT5+FmwireUux+VyHmaeqao=
