language: ruby
script: "bundle exec micron --fork $(find * -maxdepth 0 -type d | grep -v vendor)"
after_script:
  - "rake coverage"
  - "rake coveralls"

rvm:
  - 2.0.0
  - 1.9.3

branches:
  only:
    - master
