#!/usr/bin/env bash

# simple helper to run a repo script with the correct ENV
#
# usage: run <script>
#
# uses a temp BIXBY_HOME dir with repo pointing here

DIR=$(dirname $(readlink -f $0))
if [ -d $DIR/../common ]; then
  export RUBYLIB="$DIR/../common/lib:$DIR/../client/lib:$DIR/../agent/lib"
fi

export BIXBY_HOME=/tmp/bixby-repo-test
export RUBYOPT="$RUBYOPT -rbixby-client/script"

if [ ! -d $BIXBY_HOME ]; then
  mkdir -p $BIXBY_HOME/repo/
  ln -s $DIR $BIXBY_HOME/repo/vendor
fi

if [ ! -f $1 ]; then
  cmd=$(ruby -r./find_script -e "puts find_script('$1')")
else
  cmd=$1
fi

$cmd ${@:2}
