#!/usr/bin/env ruby

if ARGV.empty? then
  STDERR.puts "usage: runcheck <script> [args ...]"
  STDERR.puts
  STDERR.puts "script: absolute path or filename part"
  STDERR.puts "args:   key/value pairs (foo=bar baz=frob)"
  exit 1
end

ROOT = __dir__

require "./find_script"
script = find_script(ARGV.shift)
if script.nil? then
  STDERR.puts "couldn't find any scripts matching '#{script}'"
  exit 1
end

opts = ARGV.join(" ")
if opts == "--help" then
  cmd = [ File.join(ROOT, "./run"), script, opts ]
else
  cmd = [ File.join(ROOT, "./opts"), ARGV, "|", File.join(ROOT, "./run"), script ]
end

`which json_reformat`
cmd << "| json_reformat" if $? == 0

cmd = cmd.flatten.join(" ")
STDERR.puts cmd
exec(cmd)
