#!/usr/bin/env ruby

if ARGV.empty? then
  STDERR.puts "usage: runcheck <script> [args ...]"
  STDERR.puts
  STDERR.puts "script: absolute path or filename part"
  STDERR.puts "args:   key/value pairs (foo=bar baz=frob)"
  exit 1
end

ROOT = __dir__
$: << __dir__

require "find_script"
arg = ARGV.shift
script = find_script(arg)
if script.nil? then
  STDERR.puts "couldn't find any scripts matching '#{arg}'"
  exit 1
end

opts = ARGV.join(" ")
if opts == "--help" then
  cmd = [ File.join(ROOT, "./run"), script, opts ]
elsif opts =~ /--opt(ion)?s?/ then
  cmd = [ File.join(ROOT, "./run"), script, "--options" ]
else
  cmd = [ File.join(ROOT, "./opts"), ARGV, "|", File.join(ROOT, "./run"), script ]
end

`which json_reformat`
if $? == 0 then
  cmd << "| json_reformat"
else
  `which json_pp`
  cmd << "| json_pp" if $? == 0
end


cmd = cmd.flatten.join(" ")
STDERR.puts cmd
exec(cmd)
